import type { ParsedSource } from '../pipeline/source-parser.js';

export interface OutputMetadata {
  title: string;
  source_file: string;
  source_url?: string;
  output_type: string;
  provider: string;
  model: string;
  generated_at: string;
  word_count: number;
  warnings: string[];
}

export function buildMetadata(options: {
  source: ParsedSource;
  sourceFile: string;
  outputType: string;
  provider: string;
  model: string;
  generatedContent: string;
  warnings?: string[];
}): OutputMetadata {
  return {
    title: options.source.title,
    source_file: options.sourceFile,
    source_url: options.source.sourceUrl,
    output_type: options.outputType,
    provider: options.provider,
    model: options.model,
    generated_at: new Date().toISOString(),
    word_count: options.generatedContent.trim().split(/\s+/).filter(Boolean).length,
    warnings: options.warnings ?? [],
  };
}

export function buildReviewChecklist(title: string): string {
  return `# Review Checklist: ${title}

Review this document carefully before publishing.

## Content Review

- [ ] All factual claims verified against the original source
- [ ] Code snippets tested in a real environment
- [ ] No invented function names, API endpoints, or config values
- [ ] Unclear or extrapolated content marked or removed
- [ ] Terminology is accurate for the target audience

## Source & Attribution

- [ ] Transcript is owned by you or you have permission to use it
- [ ] Source attribution is included (if a source URL was provided)
- [ ] No verbatim reproduction of third-party copyrighted content
- [ ] Creator credit included where appropriate

## Technical Quality

- [ ] All code blocks have language tags
- [ ] All commands are tested and accurate
- [ ] File paths and config values are correct
- [ ] No placeholder values left in the output

## Hallucination Check

- [ ] No statistics or benchmarks that weren't in the original transcript
- [ ] No invented quotes or testimonials
- [ ] Conceptual code clearly labeled if not from transcript
- [ ] All links verified (if any were added)

## Publishing Readiness

- [ ] Document reviewed end-to-end
- [ ] Ready to publish: **YES / NO** *(delete one)*

---

*Generated by devdocs-forge-agent — always review AI-generated content before publishing.*
`;
}

export function buildSourceSummary(source: ParsedSource, outputType: string): string {
  return `# Source Summary

## Original Source

- **Title:** ${source.title}
- **Word count:** ${source.wordCount} words
- **Source URL:** ${source.sourceUrl ?? '(not provided)'}
- **Output type requested:** ${outputType}

## Content Overview

This document was generated from a transcript or notes file.
The source content covered the topic: **${source.title}**.

## Usage Rights Reminder

> You are responsible for ensuring you have the right to use this transcript.
> Only use content you own, created, or have explicit permission to process.
> Review the generated output for accuracy before publishing.
`;
}
