import type { Provider, GenerateOptions } from './provider.types.js';

/**
 * Mock provider — returns realistic placeholder markdown without any API calls.
 * Used as the default so the project works out-of-the-box with no API keys.
 */
export class MockProvider implements Provider {
  readonly name = 'mock';
  readonly model = 'mock-v1';

  async generate(options: GenerateOptions): Promise<string> {
    // Extract title from the transcript section of the prompt (after "---" separator)
    const transcriptSection = options.prompt.split('---').pop() ?? '';
    const h1Match = transcriptSection.match(/^#\s+(.+)$/m);
    const titleFromPrompt = options.prompt.match(/\*\*Title:\*\*\s+(.+)/);
    const title = h1Match
      ? h1Match[1].trim()
      : titleFromPrompt
        ? titleFromPrompt[1].trim()
        : 'Getting Started Guide';

    return `# ${title}

> **Note:** This output was generated by the **mock provider**. Switch to a real AI provider (OpenAI, Anthropic, or Gemini) in your \`.env\` for actual AI-generated content.

## Overview

This is a placeholder documentation page generated by devdocs-forge-agent in mock mode.

In production, this section would contain a concise overview of the topic covered in your transcript, written for your target audience.

## Prerequisites

- Familiarity with the relevant technology stack
- Access to the required tools and dependencies
- Basic understanding of the concepts covered

## Step 1: Setup

Begin by configuring your environment. This step ensures all dependencies are in place before you proceed.

\`\`\`bash
# Example setup command
npm install
\`\`\`

## Step 2: Core Concepts

This section covers the fundamental concepts introduced in the tutorial. Each concept is explained with practical context so readers can apply it immediately.

## Step 3: Implementation

Walk through the implementation step by step. Code examples are annotated to explain key decisions.

\`\`\`typescript
// Example code block
function example(): string {
  return 'This would contain real code from your transcript';
}
\`\`\`

## Common Issues

| Issue | Solution |
|-------|----------|
| Example issue 1 | Example resolution |
| Example issue 2 | Example resolution |

## Summary

This documentation was generated from a tutorial transcript. Review all code and claims before publishing.

## Next Steps

- Review this document carefully
- Test all code examples in your environment
- Add any missing context from the original source

---

*Generated by devdocs-forge-agent (mock mode) — [Switch to a real provider](../docs/PROVIDERS.md) for AI-generated content.*
`;
  }
}
